# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/schumae/Documents/EE316_Signal_Generator_ZynqBerry/Signal_Generator.srcs/sources_1/bd/top_level/ip/top_level_processing_system7_0_2/top_level_processing_system7_0_2.xci
# IP: The module: 'top_level_processing_system7_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/schumae/Documents/EE316_Signal_Generator_ZynqBerry/Signal_Generator.gen/sources_1/bd/top_level/ip/top_level_processing_system7_0_2/top_level_processing_system7_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_processing_system7_0_2'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: C:/Users/schumae/Documents/EE316_Signal_Generator_ZynqBerry/Signal_Generator.srcs/sources_1/bd/top_level/ip/top_level_processing_system7_0_2/top_level_processing_system7_0_2.xci
# IP: The module: 'top_level_processing_system7_0_2' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/schumae/Documents/EE316_Signal_Generator_ZynqBerry/Signal_Generator.gen/sources_1/bd/top_level/ip/top_level_processing_system7_0_2/top_level_processing_system7_0_2.xdc
# XDC: The top module name and the constraint reference have the same name: 'top_level_processing_system7_0_2'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
